# Site settings
title: Marketing Me
header-img: img/layout/main-bg.jpg
email: sauravsingh.srv@gmail.com
copyright_name: sauravsingh_srv
description: "Musings of a marketing fox - SauravSingh"
baseurl: "/markblog"
url: ""
twitter_username: saurav_791
github_username:  sauravsinghsrv
facebook_username: sauravsingh.king
email_username: sauravsingh.srv@gmail.com 

url:
  fivepx: https://500px.com/
  instagram: https://instagram.com/saurav_srv
  youtube: https://youtube.com/sauravsinghsrv
  twitter: https://twitter.com/saurav_791
  facebook: https://www.facebook.com/sauravsingh.king
  google: https://plus.google.com/+SauravSinghsrv
  mail: ""
  website: https://sauravsinghsrv.github.io/
  linkedin: https://www.linkedin.com/in/sauravsingh-srv/
  markblog: https://sauravsinghsrv.github.io/markblog/
  blogger: http://sauravsinghsrv.blogspot.in/
  github: https://github.com/sauravsinghsrv

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
